server:
  port: 8001
spring:
    datasource:
      url: jdbc:mysql://localhost:3308/wuhuinan?characterEncoding=utf8&useSSL=true
      username: root
      password: wuhuinan
      driver-class-name: com.mysql.jdbc.Driver

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect

    thymeleaf:
       cache: false
       mode: LEGACYHTML5


    redis:
      host: localhost
      port: 6379
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 1
      timeout: 0